language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_9178b2a730e8_key -iv $encrypted_9178b2a730e8_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
