language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_9178b2a730e8_key -iv $encrypted_9178b2a730e8_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 172.96.210.200\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- npm run build
- tar -zcf mystore.tar.gz dist/*    # 打包并压缩代码
- scp mystore.tar.gz static@172.96.210.200:~/tmp/  # 复制到生产服务器上
- ssh static@172.96.210.200 'rm -rf www/* && tar -zxf tmp/mystore.tar.gz -C www/'   # 解压